default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  database: <%= ENV.fetch("DB_NAME") { "daily_budget_development" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  sslmode: require

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  database: <%= ENV.fetch("DB_NAME") { "daily_budget_test" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "" } %>
  connect_timeout: 10
  checkout_timeout: 5
  reaping_frequency: 10

